"""Plan data — Epics 3+4 (monitor-node + monitor-browser)."""

from plan_data import body_epic, body_feature, body_task


def task(title, priority, effort, impact, goal, context, acceptance, approach, test_plan, docs="none", deps=None):
    return {
        "title": title, "priority": priority, "effort": effort, "impact": impact,
        "body": body_task(goal, context, acceptance, approach, test_plan, docs, deps),
    }


PLAN_PART2 = [
    # =====================================================================
    # EPIC 3 — monitor-node
    # =====================================================================
    {
        "title": "Epic: monitor-node — Node SDK + framework bindings",
        "priority": "P0", "effort": "XL", "impact": "high",
        "body": body_epic(
            goal="Ship `@neithly-com/monitor-node` — wraps @opentelemetry/sdk-node, exposes Sentry-shaped public API (Neithly.init/captureException/etc), auto-instrumentation (uncaughtException, HTTP), and Express/Fastify/NestJS bindings.",
            context="This is the main consumer-facing entry point on the server side. Without it, every app still has to wire ~30 lines of OTel manually. With it, three lines and done. Framework bindings (Express/Fastify/NestJS) ship as named exports so consumers pay only for what they use.",
            success_criteria=[
                "`import { Neithly } from '@neithly-com/monitor-node'; Neithly.init({dsn})` boots in under 200 ms",
                "An uncaught exception in an Express handler reaches the backend's /v1/logs",
                "An uncaught exception in a Fastify handler reaches the backend's /v1/logs",
                "A NestJS HttpException with status ≥ 500 reaches the backend; client errors (4xx) don't",
                "Tree-shaking: importing only `captureException` produces a < 50 KB ESM bundle",
            ],
            features=[
                "Feature: Transport wiring",
                "Feature: Public API (Sentry-shaped)",
                "Feature: Auto-instrumentation",
                "Feature: Express binding",
                "Feature: Fastify binding",
                "Feature: NestJS binding",
                "Feature: Tests",
            ],
        ),
        "features": [
            {
                "title": "Feature: monitor-node transport wiring",
                "priority": "P0", "effort": "M", "impact": "high",
                "body": body_feature(
                    goal="Wrap the three OTel exporters (logs/traces/metrics) with our DSN bearer header + endpoint resolution.",
                    context="OTel exporters take a headers function; we plug DSN auth + the resolved endpoint there. NodeSDK takes processors; we set sane batch defaults.",
                    acceptance=[
                        "OTLPLogExporter wrapper sets Authorization: Bearer <DSN publicKey>",
                        "Same for OTLPTraceExporter and OTLPMetricExporter",
                        "NodeSDK boots with: BatchLogRecordProcessor, BatchSpanProcessor, PeriodicExportingMetricReader",
                        "Resource attributes include service.name, service.version, deployment.environment from init options",
                    ],
                    tasks=[
                        "`feat(node): OTLPLogExporter wrapper — inject DSN bearer`",
                        "`feat(node): OTLPTraceExporter wrapper`",
                        "`feat(node): OTLPMetricExporter wrapper`",
                        "`feat(node): NodeSDK bootstrapper — resource attrs, batch processors, sampler`",
                    ],
                ),
                "tasks": [
                    task("feat(node): OTLPLogExporter wrapper — inject Authorization: Bearer <publicKey>", "P0", "S", "high",
                         "Wrap @opentelemetry/exporter-logs-otlp-http to inject the DSN bearer.",
                         "OTel exporters don't know about DSNs. Without a wrapper every consumer has to set the headers themselves — defeats the SDK's purpose.",
                         ["Exports `createLogExporter({ publicKey, endpoint })`",
                          "Returns an instance compatible with BatchLogRecordProcessor",
                          "Headers include `Authorization: Bearer <publicKey>` + `Content-Type: application/json`",
                          "Endpoint = `${endpoint}/v1/logs`"],
                         "File: `packages/node/src/transport/log-exporter.ts`. Wrap OTLPLogExporter with a custom headers function. The OTel constructor accepts a `headers` option as an object — use that.",
                         "Vitest: mock fetch, init exporter, assert request has the expected headers."),
                    task("feat(node): OTLPTraceExporter wrapper — same auth", "P0", "S", "high",
                         "Wrap @opentelemetry/exporter-trace-otlp-http for trace spans.",
                         "Identical pattern to the log exporter but on the trace pipeline.",
                         ["Exports `createTraceExporter({ publicKey, endpoint })`",
                          "Compatible with BatchSpanProcessor",
                          "Endpoint = `${endpoint}/v1/traces`"],
                         "File: `packages/node/src/transport/trace-exporter.ts`. Mirror log-exporter.ts.",
                         "Same as log-exporter spec.",
                         deps="OTLPLogExporter"),
                    task("feat(node): OTLPMetricExporter wrapper — same auth", "P0", "S", "medium",
                         "Wrap @opentelemetry/exporter-metrics-otlp-http for metric records.",
                         "Symmetric with logs/traces; metric ingest is rarer for early consumers but cheap to ship now.",
                         ["Exports `createMetricExporter({ publicKey, endpoint })`",
                          "Compatible with PeriodicExportingMetricReader",
                          "Endpoint = `${endpoint}/v1/metrics`"],
                         "File: `packages/node/src/transport/metric-exporter.ts`.",
                         "Same as log-exporter spec.",
                         deps="OTLPLogExporter"),
                    task("feat(node): NodeSDK bootstrapper — resource attrs, batch processors, sampler", "P0", "M", "high",
                         "The boot helper that ties Node SDK + the three exporters + a sane sampler together.",
                         "init({dsn, release, environment, sampling}) ends up here. Returns an SDK instance the caller can `start()`/`shutdown()`.",
                         ["Resource attributes: service.name (from init.serviceName), service.version (init.release), deployment.environment (init.environment)",
                          "BatchLogRecordProcessor with default batchSize 100 + flushInterval 5000",
                          "BatchSpanProcessor with same defaults",
                          "PeriodicExportingMetricReader with exportIntervalMillis 30000",
                          "Sampler = TraceIdRatioBased(init.sampling ?? 1.0)"],
                         "File: `packages/node/src/transport/sdk.ts`. Use @opentelemetry/sdk-node NodeSDK class. Configure all three signal pipelines.",
                         "Vitest: smoke test that SDK initialises without throwing; mock fetch and assert envelopes are POSTed after a forced flush.",
                         deps="all three exporters"),
                ],
            },
            {
                "title": "Feature: monitor-node public API (Sentry-shaped)",
                "priority": "P0", "effort": "L", "impact": "high",
                "body": body_feature(
                    goal="Expose the Neithly singleton with init/captureException/captureMessage/addBreadcrumb/setUser/setTags/setContext/withScope/flush/shutdown.",
                    context="This is the SDK's public face. The Sentry-shaped API is intentional — operators know it, so onboarding is one StackOverflow query away from familiar.",
                    acceptance=[
                        "Default export `Neithly` is a singleton",
                        "`init()` boots the SDK; calling it twice warns + no-ops",
                        "`captureException(err, context?)` returns the event id (string)",
                        "`withScope(fn)` uses AsyncLocalStorage so concurrent requests don't leak scope",
                        "`flush(timeoutMs?)` resolves when all buffered envelopes are POSTed (or rejects on timeout)",
                    ],
                    tasks=[
                        "`feat(node): Neithly.init({dsn, release, environment, integrations, sampling})`",
                        "`feat(node): Neithly.captureException(err, context?)`",
                        "`feat(node): Neithly.captureMessage(message, level?, context?)`",
                        "`feat(node): Neithly.addBreadcrumb`",
                        "`feat(node): Neithly.setUser / setTags / setContext / setExtra`",
                        "`feat(node): Neithly.withScope(fn) — AsyncLocalStorage`",
                        "`feat(node): Neithly.flush + Neithly.shutdown`",
                    ],
                ),
                "tasks": [
                    task("feat(node): Neithly.init({dsn, release, environment, integrations, sampling})", "P0", "M", "high",
                         "The boot entry point — parses DSN, instantiates NodeSDK, wires the global scope.",
                         "Sentry's init shape exactly. We re-export OTel internals for power users via `Neithly.getOtelSdk()`.",
                         ["Parses dsn via monitor-core's parseDsn",
                          "Validates init.environment matches DSN env when both present (warn on mismatch)",
                          "Default integrations: { http: true, console: true, uncaughtException: true }",
                          "Calling init twice → warn + return existing instance",
                          "Returns the Neithly instance for fluent chaining"],
                         "File: `packages/node/src/init.ts`. Module-scoped singleton state. Throws on missing dsn (loud failure at boot).",
                         "Vitest: happy path init, double init warning, missing dsn throws.",
                         deps="NodeSDK bootstrapper"),
                    task("feat(node): Neithly.captureException(err, context?) — synthesises OTLP log record", "P0", "M", "high",
                         "The most-called function in the SDK. Shape an Error, attach current scope, emit a LogRecord, return the event id.",
                         "Uses monitor-core shapeException + scope snapshot + toOtlpLogRecord then hands to the log processor.",
                         ["Returns a string event id (UUIDv4)",
                          "Snapshots the current scope (AsyncLocalStorage in node) at call time",
                          "Optional `context` overlays last (caller's tag wins)",
                          "Non-Error throws wrap via shapeException",
                          "Returns the same id even if the exporter later fails (operator can correlate)"],
                         "File: `packages/node/src/api/capture.ts`. Generate UUID with crypto.randomUUID().",
                         "Vitest: returns id, emits a LogRecord via the wired processor, scope from withScope flows through.",
                         deps="init + monitor-core wire envelopes"),
                    task("feat(node): Neithly.captureMessage(message, level?, context?)", "P0", "S", "medium",
                         "Same as captureException but for plain string messages — no exception attrs, just the body + level.",
                         "Useful for breadcrumbs of important events that aren't exceptions (e.g. \"User downgraded plan\").",
                         ["Default level: 'info'",
                          "Returns event id (string)",
                          "Snapshots scope same as captureException",
                          "Body goes into LogRecord.body, level → severityNumber"],
                         "File: `packages/node/src/api/capture.ts`. Reuse captureException's scope snapshot logic.",
                         "Vitest: emits a LogRecord with the right severity + body.",
                         deps="captureException"),
                    task("feat(node): Neithly.addBreadcrumb({category, message, data, level})", "P0", "S", "medium",
                         "Push a breadcrumb onto the active scope's ring.",
                         "Operators sprinkle these around their code to leave a trail; the trail attaches to the next captureException.",
                         ["Accepts the Breadcrumb shape from monitor-core",
                          "Pushes onto the current scope's ring",
                          "No-op (warn) if init not called",
                          "Timestamp auto-stamped if not provided"],
                         "File: `packages/node/src/api/scope.ts`. Reads current scope via AsyncLocalStorage.",
                         "Vitest: breadcrumb appears in next captureException's serialised attrs.",
                         deps="Scope + BreadcrumbRing"),
                    task("feat(node): Neithly.setUser / setTags / setContext / setExtra", "P0", "S", "medium",
                         "Mutate the active scope.",
                         "Same shape as Sentry: setUser is for identity, setTags for indexable key/values, setContext for namespaced metadata.",
                         ["setUser(user | null) — null clears the user",
                          "setTags({k:v}) — shallow merge",
                          "setContext(namespace, ctx | null) — null removes the namespace",
                          "setExtra(key, value) — single key into the 'extra' namespace"],
                         "File: `packages/node/src/api/scope.ts`. Each writes to the current scope.",
                         "Vitest: every setter reflects in the next captureException snapshot.",
                         deps="Scope"),
                    task("feat(node): Neithly.withScope(fn) — temporary scope via AsyncLocalStorage", "P0", "M", "high",
                         "Run fn inside a cloned scope; the clone auto-pops when fn returns/throws.",
                         "Per-request scoping in Node servers — Express middleware does `withScope(() => next())` and the request's tags don't leak across concurrent requests.",
                         ["Uses node:async_hooks AsyncLocalStorage",
                          "Cloned scope inherits parent's user/tags/contexts/breadcrumbs",
                          "Mutations inside withScope don't leak out",
                          "Async-safe: nested withScope works (parent state restored on inner exit)"],
                         "File: `packages/node/src/api/scope.ts`. AsyncLocalStorage instance is module-scoped.",
                         "Vitest: nested withScope state isolation, async-safe across awaits.",
                         deps="Scope"),
                    task("feat(node): Neithly.flush(timeoutMs?) + Neithly.shutdown()", "P0", "S", "medium",
                         "Flush drains all pending envelopes; shutdown is final teardown.",
                         "Critical for short-lived processes (Lambda, CLI scripts) that exit before background flushes complete.",
                         ["flush(timeoutMs) returns a Promise<boolean> — true if all flushed in time",
                          "shutdown() calls flush() then closes processors",
                          "Both are no-ops if init was never called",
                          "Default timeout 2000 ms"],
                         "File: `packages/node/src/api/lifecycle.ts`. Delegate to NodeSDK.shutdown() + each processor's forceFlush.",
                         "Vitest: a queued event is flushed; timeout returns false.",
                         deps="init"),
                ],
            },
            {
                "title": "Feature: monitor-node auto-instrumentation",
                "priority": "P0", "effort": "M", "impact": "high",
                "body": body_feature(
                    goal="Wire process-level handlers (uncaughtException, unhandledRejection) + console breadcrumbs + optional @opentelemetry/instrumentation-http for HTTP request traces.",
                    context="The whole pitch of the SDK is 'three lines and done'. Auto-instrumentation makes those three lines actually catch real bugs without extra wiring.",
                    acceptance=[
                        "An uncaught exception is captured before process exits (uses --use-strict to install the handler synchronously)",
                        "Unhandled promise rejections are captured",
                        "Console calls (info/warn/error) become breadcrumbs on the active scope",
                        "HTTP instrumentation can be disabled via init({integrations:{http:false}})",
                    ],
                    tasks=[
                        "`feat(node): hook process.on('uncaughtException') + 'unhandledRejection'`",
                        "`feat(node): integrate @opentelemetry/instrumentation-http (off via init opt-out)`",
                        "`feat(node): console breadcrumbs (log/info/warn/error → ring)`",
                    ],
                ),
                "tasks": [
                    task("feat(node): hook process.on('uncaughtException') + 'unhandledRejection'", "P0", "S", "high",
                         "Install global handlers in init() that captureException + (configurably) rethrow.",
                         "By default we don't swallow the exception — captureException + re-throw so the process still crashes (operators expect this).",
                         ["Handler installed inside init()",
                          "captureException synchronously before any rethrow",
                          "Default behaviour: rethrow (process crashes after capture)",
                          "init({captureUncaught: false}) skips this entirely",
                          "Uses process.once to avoid double-install on duplicate init"],
                         "File: `packages/node/src/integrations/process-handlers.ts`. process.on('uncaughtException', handler) + process.on('unhandledRejection', handler).",
                         "Vitest: spawn a child process with a deliberate throw, assert the mock collector saw the event.",
                         deps="captureException"),
                    task("feat(node): integrate @opentelemetry/instrumentation-http (off via init opt-out)", "P1", "M", "medium",
                         "Wire HTTP instrumentation so outgoing fetch/http requests get traced + spans become breadcrumbs.",
                         "Sentry users expect a breadcrumb per HTTP call; OTel's instrumentation-http gives us that for free via NodeSDK.",
                         ["Enabled by default via init({integrations:{http:true}})",
                          "Each HTTP request creates a span (parent if any in scope, else a root)",
                          "On request finish, a breadcrumb {category:'http', data:{method,url,status,durationMs}} is added to scope",
                          "Opted out via init({integrations:{http:false}})"],
                         "File: `packages/node/src/integrations/http.ts`. Use registerInstrumentations() with HttpInstrumentation.",
                         "Vitest: instrument a request, capture the span + breadcrumb.",
                         deps="NodeSDK bootstrapper"),
                    task("feat(node): console breadcrumbs (log/info/warn/error → ring)", "P1", "S", "medium",
                         "Monkey-patch console.log/info/warn/error to push breadcrumbs on the active scope.",
                         "Operator uses console.warn liberally during dev; we capture that trail for free.",
                         ["Patches the 4 levels (debug+log → debug; info/warn/error → matching levels)",
                          "Breadcrumb category = 'console'",
                          "Breadcrumb data.message = stringified args",
                          "Original console behaviour preserved (we call the original after the patch)",
                          "Opted out via init({integrations:{console:false}})"],
                         "File: `packages/node/src/integrations/console.ts`. Save original refs, patch, push then call original.",
                         "Vitest: console.warn → breadcrumb on next captureException.",
                         deps="addBreadcrumb"),
                ],
            },
            {
                "title": "Feature: monitor-node Express binding",
                "priority": "P1", "effort": "S", "impact": "medium",
                "body": body_feature(
                    goal="Ship Express request + error handlers that open per-request scopes + captureException uncaught errors.",
                    context="Express is the most-deployed Node framework in the org. Shipping idiomatic middleware (requestHandler + errorHandler) makes adoption a 2-line change.",
                    acceptance=[
                        "`expressRequestHandler()` opens a withScope per request, sets req tags (method, url, traceId)",
                        "`expressErrorHandler()` captureExceptions + calls next(err)",
                        "Works with Express 4 + 5",
                    ],
                    tasks=[
                        "`feat(node): expressRequestHandler() — opens an isolated scope per request`",
                        "`feat(node): expressErrorHandler() — captureException + next(err)`",
                        "`test(node): express e2e — uncaught error in handler reaches the mock collector`",
                    ],
                ),
                "tasks": [
                    task("feat(node): expressRequestHandler() — opens an isolated scope per request", "P1", "S", "medium",
                         "Express middleware that calls withScope around the rest of the chain.",
                         "Per-request scoping means request-specific tags (userId, requestId) attach to events from that request without leaking to neighbours.",
                         ["Returns a middleware (req, res, next) => void",
                          "Inside the scope, sets tags: method, url, x-request-id header if present",
                          "next() is called from inside the scope",
                          "res.on('finish') adds a breadcrumb {category:'response', data:{status, durationMs}}"],
                         "File: `packages/node/src/integrations/express.ts`. Wrap next via withScope.",
                         "Vitest with supertest: hit a route, assert scope has the request tags.",
                         deps="withScope"),
                    task("feat(node): expressErrorHandler() — captureException + next(err)", "P1", "XS", "high",
                         "The 4-arity Express error middleware that captures + forwards.",
                         "Express's error handler signature is (err, req, res, next). We capture then pass through so the app's normal error UI still renders.",
                         ["Returns a middleware (err, req, res, next) => void",
                          "captureException(err) synchronously",
                          "Calls next(err) so the app's error handler runs",
                          "Skips capture if err.status < 500 (client errors aren't bugs)"],
                         "File: `packages/node/src/integrations/express.ts`.",
                         "Vitest with supertest: throw in a route, assert collector saw the exception.",
                         deps="captureException + expressRequestHandler"),
                    task("test(node): express e2e — uncaught error in handler reaches the mock collector", "P1", "S", "medium",
                         "End-to-end test that the whole Express integration works as documented in the README.",
                         "This test stops doc drift — if the README example breaks, this test breaks too.",
                         ["supertest hits a route that throws",
                          "Mock collector receives the LogRecord with exception.* attrs",
                          "Breadcrumb chain includes request + response breadcrumbs"],
                         "File: `packages/node/test/express-e2e.spec.ts`. Use supertest + mock collector from _internal-test-utils.",
                         "The test itself.",
                         deps="expressRequestHandler + expressErrorHandler"),
                ],
            },
            {
                "title": "Feature: monitor-node Fastify binding",
                "priority": "P1", "effort": "S", "impact": "medium",
                "body": body_feature(
                    goal="Ship `fastifyPlugin` — onRequest hook opens scope, setErrorHandler captures.",
                    context="Fastify uses a plugin model + dedicated error hook. Mirror the Express integration's behaviour.",
                    acceptance=[
                        "`fastify.register(fastifyPlugin)` works",
                        "Per-request scope set in onRequest hook",
                        "setErrorHandler captures + rethrows",
                    ],
                    tasks=[
                        "`feat(node): fastifyPlugin — onRequest scope + setErrorHandler captureException`",
                        "`test(node): fastify e2e — uncaught error reaches the mock collector`",
                    ],
                ),
                "tasks": [
                    task("feat(node): fastifyPlugin — onRequest scope + setErrorHandler captureException", "P1", "S", "medium",
                         "Implement the Fastify plugin.",
                         "Fastify plugins are functions that take fastify + opts; register hooks.",
                         ["Exports `fastifyPlugin(fastify, opts, done)`",
                          "onRequest hook opens withScope around the rest of the request lifecycle",
                          "setErrorHandler captureException + rethrow (so Fastify's own handler still runs)",
                          "Skip capture for 4xx errors"],
                         "File: `packages/node/src/integrations/fastify.ts`. Use fp (fastify-plugin) wrapper for proper encapsulation.",
                         "Vitest: register plugin, throw, assert collector saw it.",
                         deps="withScope + captureException"),
                    task("test(node): fastify e2e — uncaught error reaches the mock collector", "P1", "XS", "medium",
                         "Same as Express e2e but for Fastify.",
                         "Pins the plugin's contract.",
                         ["Inject a request that throws",
                          "Collector sees LogRecord with exception.*"],
                         "File: `packages/node/test/fastify-e2e.spec.ts`. Use fastify.inject().",
                         "The test.",
                         deps="fastifyPlugin"),
                ],
            },
            {
                "title": "Feature: monitor-node NestJS binding",
                "priority": "P1", "effort": "M", "impact": "medium",
                "body": body_feature(
                    goal="Ship `NeithlyModule.forRoot()` + `NeithlyExceptionFilter` + `NeithlyInterceptor` so NestJS apps drop them into app.module.ts and get capture for free.",
                    context="The org uses NestJS heavily (neithly-auth, neithly-monitor itself). Native NestJS bindings matter.",
                    acceptance=[
                        "`NeithlyModule.forRoot({dsn, release})` is a Nest dynamic module",
                        "`NeithlyExceptionFilter` captures every uncaught exception (HttpException ≥ 500 or non-HTTP)",
                        "`NeithlyInterceptor` opens per-request scope with route + correlationId tags",
                    ],
                    tasks=[
                        "`feat(node): NeithlyModule.forRoot() — Nest dynamic module`",
                        "`feat(node): NeithlyExceptionFilter — global filter`",
                        "`feat(node): NeithlyInterceptor — request scope + correlationId`",
                        "`test(node): nest e2e — thrown HttpException + non-HTTP error both captured`",
                    ],
                ),
                "tasks": [
                    task("feat(node): NeithlyModule.forRoot() — Nest module with DI registration", "P1", "M", "medium",
                         "Dynamic module factory that calls Neithly.init + registers the filter/interceptor as global providers.",
                         "Nest pattern: dynamic modules expose forRoot/forRootAsync. We follow it.",
                         ["forRoot({dsn, release?, environment?, ...}) → DynamicModule",
                          "Calls Neithly.init under the hood once",
                          "Registers NeithlyExceptionFilter as APP_FILTER",
                          "Registers NeithlyInterceptor as APP_INTERCEPTOR",
                          "forRootAsync supports useFactory for async config (e.g. ConfigService)"],
                         "File: `packages/node/src/integrations/nestjs/module.ts`. Use APP_FILTER/APP_INTERCEPTOR DI tokens.",
                         "Vitest with @nestjs/testing: register module, assert providers wired.",
                         deps="init + captureException"),
                    task("feat(node): NeithlyExceptionFilter — global filter that captureExceptions before rethrow", "P1", "S", "medium",
                         "Implement the @Catch() filter that catches everything.",
                         "Nest's HttpException has a status; we filter 4xx out (not bugs).",
                         ["@Catch() (no args = catch all)",
                          "If exception is HttpException with status < 500, skip capture",
                          "Otherwise captureException + rethrow",
                          "Sets the route + status as context"],
                         "File: `packages/node/src/integrations/nestjs/exception-filter.ts`. Implement ExceptionFilter.",
                         "Vitest: throw HttpException(400) → not captured; throw new Error() → captured.",
                         deps="captureException"),
                    task("feat(node): NeithlyInterceptor — request-scope (correlationId, breadcrumbs)", "P1", "S", "medium",
                         "Open a per-request scope; tag with request meta + x-request-id.",
                         "Mirrors Express+Fastify per-request scoping for Nest.",
                         ["Implements NestInterceptor",
                          "Wraps intercept() in withScope",
                          "Sets tags: method, url, statusCode (post-handler), x-request-id"],
                         "File: `packages/node/src/integrations/nestjs/interceptor.ts`. RxJS handle().pipe(finalize(...)) for post-handler tagging.",
                         "Vitest: scope has the expected tags.",
                         deps="withScope"),
                    task("test(node): nest e2e — thrown HttpException + non-HTTP error both captured", "P1", "S", "medium",
                         "End-to-end test asserting the full module + filter + interceptor flow.",
                         "Pins the public contract of the NestJS binding.",
                         ["Bootstrap a minimal Nest app with NeithlyModule.forRoot",
                          "Route throwing new HttpException(500) → captured",
                          "Route throwing new Error() → captured",
                          "Route throwing HttpException(400) → NOT captured"],
                         "File: `packages/node/test/nestjs-e2e.spec.ts`. Use @nestjs/testing + supertest.",
                         "The test.",
                         deps="all three nest tasks"),
                ],
            },
            {
                "title": "Feature: monitor-node tests",
                "priority": "P0", "effort": "M", "impact": "high",
                "body": body_feature(
                    goal="Ship a mock OTLP collector + assertion helpers + an integration test against the real backend.",
                    context="The SDK's value is only as good as our confidence it sends what the backend expects. A real-backend integration test catches contract drift the moment the backend changes.",
                    acceptance=[
                        "MockOtlpCollector records POSTed envelopes + exposes helpers (assertLogRecordReceived, etc)",
                        "Integration test boots a fresh backend container, posts a captureException, asserts a row appears in /admin/projects/:id/issues",
                    ],
                    tasks=[
                        "`test(node): mock OTLP collector — assert log/trace/metric envelopes`",
                        "`test(node): integration test against local neithly-monitor backend`",
                    ],
                ),
                "tasks": [
                    task("test(node): mock OTLP collector — assert log/trace/metric envelopes match expected shape", "P0", "M", "high",
                         "Shared test util: a tiny HTTP server (Node's `http` module) that captures POSTs to /v1/* paths.",
                         "Lives in _internal-test-utils so monitor-node and monitor-browser share it.",
                         ["Listens on a random port; returns the port",
                          "Records every POST: { path, headers, body }",
                          "Exposes async `nextRequest(predicate?)` for await-based assertions",
                          "Exposes `assertLogRecord({ exception, attributes })` matcher"],
                         "File: `packages/_internal-test-utils/src/mock-collector.ts`. Use node:http; respond 200 with the OTLP partial-success shape.",
                         "Vitest exercises the matcher.",
                         deps="vitest workspace setup"),
                    task("test(node): integration test against the local neithly-monitor backend", "P1", "L", "high",
                         "End-to-end test that boots the real backend (via docker compose) and asserts an Issue appears after captureException.",
                         "Real contract validation. Pins backend ↔ SDK alignment for v0.1.",
                         ["docker compose up the backend (postgres + monitor)",
                          "Seed a Project + DSN",
                          "Boot monitor-node with the DSN",
                          "captureException(new Error('e2e')) + flush",
                          "Hit /admin/.../issues, assert a row matches the exception"],
                         "File: `packages/node/test/backend-e2e.spec.ts`. Use testcontainers-node + axios for the admin API.",
                         "The test itself.",
                         deps="all monitor-node features + mock collector for backup"),
                ],
            },
        ],
    },
    # =====================================================================
    # EPIC 4 — monitor-browser
    # =====================================================================
    {
        "title": "Epic: monitor-browser — Browser SDK",
        "priority": "P0", "effort": "L", "impact": "high",
        "body": body_epic(
            goal="Ship `@neithly-com/monitor-browser` — fetch-based OTLP exporter (no Node deps), Sentry-shaped public API, window.onerror + unhandledrejection + fetch/XHR/console auto-instrumentation, sendBeacon fallback on pagehide.",
            context="Browser environments have very different constraints than Node: no AsyncLocalStorage, no node:http, no graceful shutdown. The exporter is fetch-based; on pagehide we send via navigator.sendBeacon to make sure in-flight envelopes leave.",
            success_criteria=[
                "`import { Neithly } from '@neithly-com/monitor-browser'; Neithly.init({dsn})` boots in under 30 ms",
                "An uncaught error in a button handler reaches the backend",
                "An unhandled promise rejection reaches the backend",
                "fetch and XHR calls become breadcrumbs",
                "On pagehide, queued envelopes flush via sendBeacon",
            ],
            features=[
                "Feature: Browser transport (fetch + sendBeacon)",
                "Feature: Browser public API",
                "Feature: Browser auto-instrumentation",
                "Feature: Browser tests",
            ],
        ),
        "features": [
            {
                "title": "Feature: Browser transport (fetch + sendBeacon)",
                "priority": "P0", "effort": "M", "impact": "high",
                "body": body_feature(
                    goal="Three OTLP exporters built on fetch (no Node deps) + a sendBeacon fallback for pagehide.",
                    context="OTel's @opentelemetry/exporter-logs-otlp-http uses XHR under the hood which doesn't survive pagehide cleanly. We hand-roll fetch + sendBeacon to be reliable.",
                    acceptance=[
                        "fetch-based exporters for logs/traces/metrics",
                        "On `pagehide` (or `visibilitychange → hidden`), in-flight queue flushed via sendBeacon",
                        "Bundle size: < 30 KB minified+gzipped (excluding @opentelemetry/api types)",
                    ],
                    tasks=[
                        "`feat(browser): fetch-based OTLPLogExporter`",
                        "`feat(browser): fetch-based OTLPTraceExporter`",
                        "`feat(browser): fetch-based OTLPMetricExporter`",
                        "`feat(browser): sendBeacon fallback on pagehide`",
                    ],
                ),
                "tasks": [
                    task("feat(browser): fetch-based OTLPLogExporter — DSN bearer + JSON body", "P0", "M", "high",
                         "Hand-rolled OTLPLogRecordExporter that uses fetch + DSN auth.",
                         "OTel's official browser exporter is XHR-based; we use fetch for better pagehide behaviour.",
                         ["Implements LogRecordExporter interface",
                          "POST to /v1/logs with Authorization: Bearer <publicKey>",
                          "Body is OTLP/HTTP/JSON (uses toOtlpLogRecord from core)",
                          "Returns ExportResult.SUCCESS / FAILURE per OTel spec"],
                         "File: `packages/browser/src/transport/log-exporter.ts`. Use fetch() with credentials: 'omit', mode: 'cors'.",
                         "Vitest jsdom: mock fetch, verify request shape.",
                         deps="monitor-core endpoints + toOtlpLogRecord"),
                    task("feat(browser): fetch-based OTLPTraceExporter", "P0", "S", "medium",
                         "Mirror the log exporter for trace spans.",
                         "Symmetric; same fetch + DSN pattern.",
                         ["Implements SpanExporter",
                          "Endpoint /v1/traces",
                          "Body is OTLP trace JSON"],
                         "File: `packages/browser/src/transport/trace-exporter.ts`.",
                         "Vitest jsdom.",
                         deps="OTLPLogExporter (browser)"),
                    task("feat(browser): fetch-based OTLPMetricExporter", "P1", "S", "low",
                         "Mirror for metrics. Lower priority — most browser consumers won't emit metrics initially.",
                         "Symmetric.",
                         ["Implements PushMetricExporter",
                          "Endpoint /v1/metrics"],
                         "File: `packages/browser/src/transport/metric-exporter.ts`.",
                         "Vitest jsdom.",
                         deps="OTLPLogExporter (browser)"),
                    task("feat(browser): sendBeacon fallback on pagehide for in-flight envelopes", "P0", "S", "high",
                         "On pagehide/visibilitychange-hidden, flush any queued envelopes via navigator.sendBeacon.",
                         "fetch in the background can be killed when the page unloads. sendBeacon is designed for this.",
                         ["Listens to 'pagehide' + 'visibilitychange'",
                          "If queue non-empty, posts each via navigator.sendBeacon",
                          "Fallback to fetch with keepalive:true if sendBeacon unavailable",
                          "No-op if no envelopes pending"],
                         "File: `packages/browser/src/transport/pagehide.ts`. addEventListener with passive:true to avoid scroll-blocking.",
                         "Vitest jsdom: simulate pagehide, assert beacon called.",
                         deps="OTLPLogExporter (browser)"),
                ],
            },
            {
                "title": "Feature: Browser public API",
                "priority": "P0", "effort": "M", "impact": "high",
                "body": body_feature(
                    goal="Same Neithly singleton shape as monitor-node, adapted to the browser (no AsyncLocalStorage; single global scope).",
                    context="Sentry-shape symmetry between node + browser is the SDK's promise. Public API matches monitor-node exactly except for runtime-specific differences (withScope is sync-only, not AsyncLocalStorage).",
                    acceptance=[
                        "Same named exports as monitor-node",
                        "withScope is sync — clones the active scope, mutations don't leak after fn returns",
                        "Tree-shakeable: importing only captureException doesn't pull in fetch instrumentation",
                    ],
                    tasks=[
                        "`feat(browser): Neithly.init({dsn, release, environment})`",
                        "`feat(browser): captureException / captureMessage / addBreadcrumb / setUser / setTags / withScope`",
                        "`feat(browser): Neithly.flush + Neithly.shutdown`",
                    ],
                ),
                "tasks": [
                    task("feat(browser): Neithly.init({dsn, release, environment, tunnel?})", "P0", "M", "high",
                         "Browser-flavoured init — installs handlers + wires the SDK.",
                         "tunnel option lets consumers proxy through their own backend (CORS workaround).",
                         ["Parses dsn",
                          "Default integrations: { onerror: true, fetch: true, xhr: true, console: true }",
                          "Sets up the singleton scope",
                          "Double init warns + returns existing",
                          "tunnel option overrides the endpoint"],
                         "File: `packages/browser/src/init.ts`.",
                         "Vitest jsdom: init twice → warn; tunnel overrides URL.",
                         deps="all three browser exporters + monitor-core"),
                    task("feat(browser): captureException + captureMessage + addBreadcrumb + setUser + setTags + withScope", "P0", "M", "high",
                         "All the Sentry-shaped public API in one task — shorter implementations vs Node because no AsyncLocalStorage.",
                         "Single global scope; withScope clones + restores synchronously.",
                         ["captureException returns event id, snapshots scope, emits LogRecord",
                          "captureMessage same with body+level",
                          "addBreadcrumb push to global ring",
                          "setUser/setTags/setContext mutate global scope",
                          "withScope: scope.clone() → fn(child) → restore"],
                         "File: `packages/browser/src/api/*.ts`. Mirror node files but synchronous scope.",
                         "Vitest jsdom for each.",
                         deps="init (browser)"),
                    task("feat(browser): Neithly.flush + Neithly.shutdown", "P0", "S", "medium",
                         "Flush + shutdown for browser. Important for SPA route changes if the consumer wants a guaranteed flush.",
                         "Same shape as node but adapted to fetch processors.",
                         ["flush(timeoutMs?) → Promise<boolean>",
                          "shutdown() → flush + remove event listeners + null-out singleton"],
                         "File: `packages/browser/src/api/lifecycle.ts`.",
                         "Vitest jsdom.",
                         deps="init (browser)"),
                ],
            },
            {
                "title": "Feature: Browser auto-instrumentation",
                "priority": "P0", "effort": "M", "impact": "high",
                "body": body_feature(
                    goal="Hook window.onerror, unhandledrejection, fetch, XHR, console.",
                    context="A SPA's lifeblood: catch unexpected throws + the call trail leading to them.",
                    acceptance=[
                        "window.onerror handler captures + chains the original handler",
                        "unhandledrejection same",
                        "fetch + XHR instrumentation emit timing + status breadcrumbs",
                        "console breadcrumbs match the node SDK's shape",
                    ],
                    tasks=[
                        "`feat(browser): window.onerror handler → captureException`",
                        "`feat(browser): unhandledrejection → captureException`",
                        "`feat(browser): fetch instrumentation — timing + status + breadcrumb`",
                        "`feat(browser): XMLHttpRequest instrumentation — same`",
                        "`feat(browser): console breadcrumbs`",
                    ],
                ),
                "tasks": [
                    task("feat(browser): window.onerror handler → captureException", "P0", "S", "high",
                         "Replace window.onerror with our handler; preserve any pre-existing one.",
                         "The classic 'catch all uncaught errors' hook.",
                         ["Saves original window.onerror",
                          "Installs handler that captures + calls original",
                          "Returns false (don't swallow)",
                          "Opted out via init({integrations:{onerror:false}})"],
                         "File: `packages/browser/src/integrations/onerror.ts`.",
                         "Vitest jsdom.",
                         deps="captureException (browser)"),
                    task("feat(browser): unhandledrejection → captureException", "P0", "S", "high",
                         "Same pattern for promise rejections.",
                         "Modern apps throw via promise rejection more than synchronous throws.",
                         ["Listens via window.addEventListener('unhandledrejection')",
                          "Captures event.reason as the exception",
                          "Doesn't preventDefault — devtools still see it",
                          "Opted out via init({integrations:{unhandledrejection:false}})"],
                         "File: `packages/browser/src/integrations/unhandledrejection.ts`.",
                         "Vitest jsdom: trigger an unhandled rejection.",
                         deps="captureException (browser)"),
                    task("feat(browser): fetch instrumentation — timing + status + breadcrumb", "P0", "M", "medium",
                         "Patch window.fetch to wrap each call with timing + breadcrumb.",
                         "Breadcrumb data: { method, url, status, durationMs }.",
                         ["Saves original fetch",
                          "Wraps so each call timestamped, status captured",
                          "Pushes breadcrumb on settle (success + failure)",
                          "5xx response → breadcrumb level: 'warning'",
                          "Opted out via init({integrations:{fetch:false}})"],
                         "File: `packages/browser/src/integrations/fetch.ts`.",
                         "Vitest jsdom: stub fetch, verify breadcrumb on resolve + reject.",
                         deps="addBreadcrumb (browser)"),
                    task("feat(browser): XMLHttpRequest instrumentation — same", "P1", "M", "low",
                         "Patch XHR.open + send so XHR calls also become breadcrumbs.",
                         "Some apps (especially older ones) still use XHR; cover them.",
                         ["Patches XHR.prototype.open + send",
                          "Captures method, url, status, durationMs",
                          "Pushes breadcrumb on readystatechange === DONE",
                          "Opted out via init({integrations:{xhr:false}})"],
                         "File: `packages/browser/src/integrations/xhr.ts`.",
                         "Vitest jsdom: create XHR, send, verify breadcrumb.",
                         deps="addBreadcrumb (browser)"),
                    task("feat(browser): console breadcrumbs (info/warn/error → ring)", "P1", "S", "medium",
                         "Same as the node console patch.",
                         "Symmetric API.",
                         ["Patches console.{log,info,warn,error}",
                          "Pushes breadcrumb with category 'console'",
                          "Original behaviour preserved"],
                         "File: `packages/browser/src/integrations/console.ts`.",
                         "Vitest jsdom.",
                         deps="addBreadcrumb (browser)"),
                ],
            },
            {
                "title": "Feature: Browser tests",
                "priority": "P0", "effort": "S", "impact": "high",
                "body": body_feature(
                    goal="jsdom-based unit suites covering the full public API + each integration.",
                    context="Browser SDK has more moving parts than node (window globals + lifecycle events). Comprehensive jsdom coverage compensates for lack of real-browser CI in v0.1.",
                    acceptance=[
                        "Each integration has at least one happy-path + one error-path spec",
                        "Public API surface (captureException, captureMessage, etc) has snapshot-pinned envelope shape",
                        "Pagehide path tested via simulated event dispatch",
                    ],
                    tasks=[
                        "`test(browser): jsdom unit — captureException end-to-end`",
                        "`test(browser): jsdom unit — fetch instrumentation breadcrumb shape`",
                        "`test(browser): jsdom unit — pagehide sendBeacon path`",
                    ],
                ),
                "tasks": [
                    task("test(browser): jsdom unit — captureException end-to-end shape", "P0", "S", "high",
                         "Snapshot test the OTLP body produced by a captureException call.",
                         "Pins the wire format; downstream backend depends on it.",
                         ["Stub fetch, capture an exception, assert body matches snapshot",
                          "Asserts: exception.* attrs, breadcrumbs serialised, scope flattened"],
                         "File: `packages/browser/test/capture-end-to-end.spec.ts`.",
                         "The test.",
                         deps="captureException (browser)"),
                    task("test(browser): jsdom unit — fetch instrumentation breadcrumb shape", "P0", "S", "medium",
                         "Pin the breadcrumb shape from fetch instrumentation.",
                         "Operators rely on these fields being present in breadcrumb data.",
                         ["Trigger a fetch, capture an exception, assert breadcrumb in payload",
                          "Asserts: category 'http', data.method, data.url, data.status, data.durationMs"],
                         "File: `packages/browser/test/fetch-breadcrumb.spec.ts`.",
                         "The test.",
                         deps="fetch instrumentation"),
                    task("test(browser): jsdom unit — pagehide sendBeacon path", "P0", "S", "medium",
                         "Pin the sendBeacon failover behaviour.",
                         "This is the failure mode that loses events without our handler.",
                         ["Queue an envelope (don't await flush)",
                          "Dispatch pagehide event",
                          "Assert navigator.sendBeacon was called with the right URL + body"],
                         "File: `packages/browser/test/pagehide.spec.ts`. Stub navigator.sendBeacon.",
                         "The test.",
                         deps="sendBeacon fallback"),
                ],
            },
        ],
    },
]
