"""Plan data — Epics 5+6+7 (monitor-react + monitor-cli + Docs)."""

from plan_data import body_epic, body_feature, body_task


def task(title, priority, effort, impact, goal, context, acceptance, approach, test_plan, docs="none", deps=None):
    return {
        "title": title, "priority": priority, "effort": effort, "impact": impact,
        "body": body_task(goal, context, acceptance, approach, test_plan, docs, deps),
    }


PLAN_PART3 = [
    # =====================================================================
    # EPIC 5 — monitor-react
    # =====================================================================
    {
        "title": "Epic: monitor-react — React bindings",
        "priority": "P1", "effort": "M", "impact": "medium",
        "body": body_epic(
            goal="Ship `@neithly-com/monitor-react` — `<NeithlyErrorBoundary>` + `useNeithlyScope` hook + react-router v6 navigation breadcrumbs.",
            context="React errors don't naturally bubble to window.onerror — error boundaries are the canonical hook. monitor-react gives a one-component opt-in that captures + falls back to a user-provided UI.",
            success_criteria=[
                "`<NeithlyErrorBoundary>` catches descendant errors + sends to backend + renders fallback",
                "`useNeithlyScope({user, tags})` sets scope from a React tree branch",
                "react-router v6 navigations are breadcrumbs",
            ],
            features=[
                "Feature: ErrorBoundary",
                "Feature: react-router instrumentation",
            ],
        ),
        "features": [
            {
                "title": "Feature: ErrorBoundary",
                "priority": "P1", "effort": "S", "impact": "medium",
                "body": body_feature(
                    goal="Class component `<NeithlyErrorBoundary>` that captures + renders a fallback prop.",
                    context="Functional components can't catch render errors — only class components via componentDidCatch. We provide the canonical one.",
                    acceptance=[
                        "Captures via componentDidCatch + getDerivedStateFromError",
                        "fallback prop = ReactNode or (error, reset) => ReactNode",
                        "reset() clears the error state",
                        "Optional onError prop fires after capture",
                    ],
                    tasks=[
                        "`feat(react): <NeithlyErrorBoundary> — captureException + fallback prop`",
                        "`feat(react): useNeithlyScope hook — set tags/user from component tree`",
                        "`test(react): @testing-library — boundary catches + sends event`",
                    ],
                ),
                "tasks": [
                    task("feat(react): <NeithlyErrorBoundary> — captureException + fallback prop", "P1", "S", "medium",
                         "Implement the boundary class.",
                         "componentDidCatch is the only React-supported way to catch render errors.",
                         ["Props: children, fallback (ReactNode | (err, reset) => ReactNode), onError (optional)",
                          "On error: captureException, store state.error, render fallback",
                          "reset() clears state.error and re-renders children",
                          "Forwards error context (componentStack) as a tag"],
                         "File: `packages/react/src/error-boundary.tsx`. Class component with state {error: Error | null}.",
                         "@testing-library: render <ErrorBoundary><Bomb /></ErrorBoundary>, click reset, verify capture + recovery.",
                         deps="captureException (browser)"),
                    task("feat(react): useNeithlyScope hook — set tags/user from component tree", "P1", "XS", "low",
                         "Hook to set scope from a React branch — auto-restores on unmount.",
                         "Like Sentry's withScope but tied to component lifecycle.",
                         ["Signature: useNeithlyScope({user?, tags?, contexts?})",
                          "Sets scope on mount; restores prior values on unmount",
                          "Re-runs on prop changes (deps tracked)"],
                         "File: `packages/react/src/use-scope.ts`. useEffect with cleanup that snapshots+restores.",
                         "@testing-library: mount + unmount cycle.",
                         deps="setUser/setTags (browser)"),
                    task("test(react): @testing-library — boundary catches + sends event", "P1", "XS", "low",
                         "Pin the boundary's behaviour with RTL.",
                         "Doc-driven test: matches the README example exactly.",
                         ["Mount <NeithlyErrorBoundary fallback={...}><Bomb /></NeithlyErrorBoundary>",
                          "Bomb throws on render → fallback renders",
                          "Stubbed captureException received the error"],
                         "File: `packages/react/test/error-boundary.spec.tsx`. Use vi.spyOn on captureException.",
                         "The test.",
                         deps="ErrorBoundary"),
                ],
            },
            {
                "title": "Feature: react-router instrumentation",
                "priority": "P2", "effort": "S", "impact": "low",
                "body": body_feature(
                    goal="Track react-router v6 navigation as breadcrumbs.",
                    context="Sentry-style: 'user clicked here, then here, then crashed'.",
                    acceptance=[
                        "useTrackRouter() reads useLocation + pushes a breadcrumb on each change",
                        "wrapCreateBrowserRouter optionally wraps + auto-tracks",
                    ],
                    tasks=[
                        "`feat(react): useTrackRouter — react-router v6 navigation breadcrumbs`",
                        "`feat(react): wrapCreateBrowserRouter — auto-track route changes`",
                        "`test(react): router integration test`",
                    ],
                ),
                "tasks": [
                    task("feat(react): useTrackRouter — react-router v6 navigation breadcrumbs", "P2", "S", "low",
                         "Hook that emits a breadcrumb on every useLocation change.",
                         "Drop into the root and forget.",
                         ["Uses useLocation",
                          "Pushes breadcrumb {category:'navigation', data:{from, to, search}}",
                          "Initial mount: no breadcrumb (no 'from')"],
                         "File: `packages/react/src/use-track-router.ts`. useEffect with location dep.",
                         "@testing-library: mount with MemoryRouter, navigate, assert breadcrumb count.",
                         deps="addBreadcrumb (browser)"),
                    task("feat(react): wrapCreateBrowserRouter — auto-track route changes", "P2", "S", "low",
                         "Higher-order wrapper around createBrowserRouter that injects the hook into every route.",
                         "Saves the consumer from putting useTrackRouter in their root layout.",
                         ["Wraps createBrowserRouter; returns the wrapped router",
                          "Injects a small <RouterTracker /> at the top of each route's element",
                          "Works with data routers (no-op on non-data routers)"],
                         "File: `packages/react/src/wrap-router.ts`.",
                         "@testing-library: assert tracker mounted.",
                         deps="useTrackRouter"),
                    task("test(react): router integration test", "P2", "XS", "low",
                         "Test that ties hook + router wrap together.",
                         "Pins the integration.",
                         ["Mount a 3-route app, navigate twice",
                          "Assert 2 navigation breadcrumbs on next captureException"],
                         "File: `packages/react/test/router-integration.spec.tsx`.",
                         "The test.",
                         deps="useTrackRouter + wrapCreateBrowserRouter"),
                ],
            },
        ],
    },
    # =====================================================================
    # EPIC 6 — monitor-cli
    # =====================================================================
    {
        "title": "Epic: monitor-cli — CLI for releases + sourcemaps",
        "priority": "P1", "effort": "M", "impact": "high",
        "body": body_epic(
            goal="Ship `@neithly-com/monitor-cli` — `monitor releases create` + `monitor sourcemaps upload` so CI pipelines can register releases and upload sourcemaps without curl wrangling.",
            context="The backend already has the endpoints (POST /projects/:id/releases + POST /releases/:id/files). The CLI just adds friendly UX + sane defaults + git auto-detection.",
            success_criteria=[
                "`monitor releases create --version $RELEASE` works in a one-liner",
                "`monitor sourcemaps upload dist/**/*.map --release $RELEASE` uploads + dedups",
                "Auto-detects version from git tag/SHA when omitted",
                "Idempotent: re-runs are no-ops",
            ],
            features=[
                "Feature: CLI scaffold",
                "Feature: Releases command",
                "Feature: Source-maps command",
            ],
        ),
        "features": [
            {
                "title": "Feature: CLI scaffold",
                "priority": "P1", "effort": "S", "impact": "medium",
                "body": body_feature(
                    goal="Commander-based CLI structure + config loader (env + .neithlyrc + flags).",
                    context="Clean scaffold means subcommands are easy to add. Config loader follows the standard precedence: flag > env > file.",
                    acceptance=[
                        "`monitor --help` shows the command tree",
                        "Config keys: apiUrl, apiToken, projectSlug",
                        "Config can come from env (NEITHLY_*), .neithlyrc (json/yaml), or flags",
                    ],
                    tasks=[
                        "`feat(cli): commander setup — root + subcommands + version/help`",
                        "`feat(cli): config loader — env + .neithlyrc + flags`",
                        "`feat(cli): MonitorClient — auth via NEITHLY_API_TOKEN, base from MONITOR_API_URL`",
                    ],
                ),
                "tasks": [
                    task("feat(cli): commander setup — root + subcommands + version/help", "P1", "S", "medium",
                         "Wire commander as the CLI base; add the two top-level commands (releases, sourcemaps).",
                         "Commander is a lean industry-standard pick.",
                         ["`monitor` root command with --version + --help",
                          "Subcommand `monitor releases` with nested `create`",
                          "Subcommand `monitor sourcemaps` with nested `upload`",
                          "Each subcommand has its own --help"],
                         "File: `packages/cli/src/index.ts`. Use commander.js + chalk for color.",
                         "Vitest: spawn the CLI binary, check --help output.",
                         deps="tsup builds the CLI with the shebang"),
                    task("feat(cli): config loader — env vars + .neithlyrc + flags", "P1", "S", "medium",
                         "Resolve config keys with the precedence: flag > env > file > prompt.",
                         "Mirrors npm/gh CLIs.",
                         ["Env: NEITHLY_API_URL, NEITHLY_API_TOKEN, NEITHLY_PROJECT_SLUG",
                          ".neithlyrc: search up from cwd; JSON or YAML",
                          "Missing required key → friendly error + suggest the env var name"],
                         "File: `packages/cli/src/config.ts`. Use cosmiconfig for file loading.",
                         "Vitest: each precedence path.",
                         deps="commander setup"),
                    task("feat(cli): MonitorClient — auth via NEITHLY_API_TOKEN, base from MONITOR_API_URL", "P1", "S", "medium",
                         "Tiny HTTP client used by every command — handles auth + base URL.",
                         "Wraps fetch with the Authorization header.",
                         ["client.get/post/patch/delete with typed bodies",
                          "Adds Authorization: Bearer <NEITHLY_API_TOKEN>",
                          "Throws ApiError with status + body on non-2xx"],
                         "File: `packages/cli/src/api-client.ts`. Plain fetch wrapper.",
                         "Vitest: mock fetch, assert headers.",
                         deps="config loader"),
                ],
            },
            {
                "title": "Feature: Releases command",
                "priority": "P1", "effort": "S", "impact": "high",
                "body": body_feature(
                    goal="`monitor releases create [--version <v>] [--project <slug>]` — registers a release on the backend.",
                    context="CI pipelines call this on tag/deploy to log the release. The endpoint is idempotent on (projectId, version) so re-runs are safe.",
                    acceptance=[
                        "Without --version, auto-detect from git tag (fallback: short SHA)",
                        "Without --project, read from config",
                        "Idempotent: re-running returns the existing release",
                        "Output: the release id (machine-parseable for piping into sourcemaps upload)",
                    ],
                    tasks=[
                        "`feat(cli): monitor releases create --version <v> --project <slug>`",
                        "`feat(cli): auto-detect --version from git tag, fallback to git short sha`",
                        "`test(cli): releases create — mocked HTTP + git seam`",
                    ],
                ),
                "tasks": [
                    task("feat(cli): monitor releases create --version <v> --project <slug>", "P1", "S", "high",
                         "Implement the releases create command.",
                         "Calls POST /projects/<slug>/releases.",
                         ["Required: --version (or auto-detect)",
                          "POST body: {version}",
                          "On 2xx: print release id",
                          "On 409 (existing version): print existing id (still success)"],
                         "File: `packages/cli/src/commands/releases-create.ts`. Use MonitorClient.",
                         "Vitest: mock client, check POST shape.",
                         deps="MonitorClient"),
                    task("feat(cli): auto-detect --version from git tag, fallback to git short sha", "P1", "S", "medium",
                         "When --version is missing, shell out to git to derive it.",
                         "CI typically runs at a tag or commit; we default to the obvious answer.",
                         ["If --version provided, use it",
                          "Else: git describe --tags --exact-match (use tag)",
                          "Else: git rev-parse --short HEAD (use SHA)",
                          "If git unavailable: friendly error suggesting --version explicitly"],
                         "File: `packages/cli/src/git.ts`. child_process.execSync wrapper.",
                         "Vitest: mock execSync, test each path.",
                         deps="releases create base command"),
                    task("test(cli): releases create — mocked HTTP + git seam", "P1", "XS", "low",
                         "Full command path with mocked HTTP + git.",
                         "Pins the command's contract.",
                         ["With --version: POST body matches",
                          "Without --version: auto-detect runs",
                          "On 409: still success, prints existing id"],
                         "File: `packages/cli/test/releases-create.spec.ts`.",
                         "The test.",
                         deps="releases create + git auto-detect"),
                ],
            },
            {
                "title": "Feature: Source-maps command",
                "priority": "P1", "effort": "M", "impact": "high",
                "body": body_feature(
                    goal="`monitor sourcemaps upload <glob> --release <v>` — uploads each .map file matched by the glob.",
                    context="Source maps are how the backend's symbolicator de-minifies stack traces. Uploading them is the operator's most error-prone CI step; the CLI must be bulletproof.",
                    acceptance=[
                        "Accepts glob patterns",
                        "Idempotent (skip if backend already has SHA-256)",
                        "Parallel uploads up to 4",
                        "Progress UI shows file/N counter + bytes",
                    ],
                    tasks=[
                        "`feat(cli): monitor sourcemaps upload <glob> --release <v>`",
                        "`feat(cli): multipart upload + parallel up to 4 with progress UI`",
                        "`feat(cli): SHA-256 dedup — skip if backend has the file`",
                        "`test(cli): sourcemaps upload — happy path + 4xx surface + idempotent re-upload`",
                    ],
                ),
                "tasks": [
                    task("feat(cli): monitor sourcemaps upload <glob> --release <v>", "P1", "M", "high",
                         "Glob match → batch upload via the release-files endpoint.",
                         "Glob support handles dist/**/*.map cleanly.",
                         ["Accepts a glob (single argument)",
                          "Resolves the release id from --release version (calls /projects/:slug/releases?version=)",
                          "For each matched .map file, POST multipart to /releases/<id>/files",
                          "Stops on first non-retryable error (network blip is retryable)"],
                         "File: `packages/cli/src/commands/sourcemaps-upload.ts`. Use globby + form-data + node-fetch.",
                         "Vitest: mock filesystem + client, run command.",
                         deps="MonitorClient + releases create (for the lookup)"),
                    task("feat(cli): multipart upload + parallel up to 4 with progress UI", "P1", "S", "medium",
                         "Add parallel upload + ora spinner / progress bar.",
                         "Single-threaded uploads are too slow for big SPAs (50+ source maps).",
                         ["Concurrency = 4 by default; configurable with --concurrency",
                          "Progress: 'Uploading 12/47 (file.js.map, 432 KB)'",
                          "Per-file retry: 2 attempts on 5xx, none on 4xx",
                          "Final summary: N uploaded, M skipped (dedup), 0 failed"],
                         "File: same as upload command + p-limit for concurrency + ora for UI.",
                         "Vitest: simulate slow uploads, ensure concurrency cap holds.",
                         deps="sourcemaps upload base command"),
                    task("feat(cli): SHA-256 dedup — skip if backend already has the file", "P1", "S", "medium",
                         "Pre-compute SHA-256, GET /releases/<id>/files?sha=…, skip if present.",
                         "Backend already dedups on insert; client-side check saves bandwidth + makes the progress UI honest.",
                         ["Compute SHA-256 of each file before upload",
                          "Batch-check: GET /releases/<id>/files returns list with SHA-256 column",
                          "Skip + log 'already uploaded'",
                          "Falsy on 404 (release not found) — surface friendly error"],
                         "File: same. Use crypto.createHash.",
                         "Vitest: pre-seed mock backend with one file's hash, upload, verify skip.",
                         deps="sourcemaps upload + parallel"),
                    task("test(cli): sourcemaps upload — happy path + 4xx surface + idempotent re-upload", "P1", "S", "medium",
                         "Full coverage of the command's failure modes.",
                         "Pins the user-facing error UX.",
                         ["3-file glob → 3 uploads with correct progress",
                          "Backend 401 → friendly 'Auth failed' message",
                          "Backend 404 (release) → friendly 'Release not found, run releases create first'",
                          "Re-running with same files → all skipped"],
                         "File: `packages/cli/test/sourcemaps-upload.spec.ts`.",
                         "The test.",
                         deps="all sourcemaps tasks"),
                ],
            },
        ],
    },
    # =====================================================================
    # EPIC 7 — Docs & examples
    # =====================================================================
    {
        "title": "Epic: Docs & examples",
        "priority": "P1", "effort": "M", "impact": "high",
        "body": body_epic(
            goal="Ship per-package READMEs, root architecture docs, ADRs, and two example apps so contributors and consumers can ramp without reading source.",
            context="Without docs the SDK won't be adopted. Each package README is a copy-paste setup + a concrete example. Root docs explain the architectural choices (Sentry-shape over OTel, dual package shipping, etc).",
            success_criteria=[
                "5 per-package READMEs are sufficient to install + integrate the package",
                "Root README explains 'which package do I want?' in 30 seconds",
                "examples/express-node and examples/react-spa boot + show their first captured event end-to-end",
            ],
            features=[
                "Feature: Per-package READMEs",
                "Feature: Root docs",
                "Feature: Example apps",
            ],
        ),
        "features": [
            {
                "title": "Feature: Per-package READMEs",
                "priority": "P1", "effort": "M", "impact": "high",
                "body": body_feature(
                    goal="Each package has a README that's enough to install + initialize + see a first event.",
                    context="No 'see the root docs' redirects. Each package's README stands alone.",
                    acceptance=[
                        "Install snippet (one line)",
                        "Quickstart (3-5 lines)",
                        "Concrete example with capture",
                        "API reference table (or link to TypeScript types)",
                    ],
                    tasks=[
                        "`docs(node): README + 30-line copy-paste setup`",
                        "`docs(browser): README + Vite / Webpack setup`",
                        "`docs(react): README + ErrorBoundary + router examples`",
                        "`docs(cli): README + GitHub Actions snippet`",
                        "`docs(core): README explaining the workspace-only role`",
                    ],
                ),
                "tasks": [
                    task("docs(node): README + 30-line copy-paste setup", "P1", "S", "high",
                         "Write the monitor-node README.",
                         "Most adopters land here first.",
                         ["Install line: `pnpm add @neithly-com/monitor-node`",
                          "Quickstart: 3-line init + a captureException example",
                          "Express section: middleware install",
                          "Fastify section",
                          "NestJS section",
                          "Auto-instrumentation list with opt-out flags"],
                         "File: `packages/node/README.md`.",
                         "Manual review: a new contributor can boot a sample app from the README alone.",
                         deps="all monitor-node features merged"),
                    task("docs(browser): README + Vite / Webpack setup snippets", "P1", "S", "high",
                         "monitor-browser README.",
                         "Vite + Webpack are the two bundlers consumers use.",
                         ["Install + init",
                          "Vite snippet (main.ts import)",
                          "Webpack snippet",
                          "Source maps + Release flow link to monitor-cli"],
                         "File: `packages/browser/README.md`.",
                         "Manual review.",
                         deps="all monitor-browser features merged"),
                    task("docs(react): README + ErrorBoundary + router examples", "P1", "XS", "medium",
                         "monitor-react README.",
                         "Companion to monitor-browser.",
                         ["Install + init link",
                          "<NeithlyErrorBoundary> wrap App example",
                          "useTrackRouter setup",
                          "wrapCreateBrowserRouter setup"],
                         "File: `packages/react/README.md`.",
                         "Manual review.",
                         deps="all monitor-react features merged"),
                    task("docs(cli): README + GitHub Actions snippet", "P1", "S", "high",
                         "monitor-cli README.",
                         "CI-focused: GH Actions snippet is the highest-value example.",
                         ["Install in CI (NEITHLY_API_TOKEN secret)",
                          "monitor releases create example",
                          "monitor sourcemaps upload example with Vite glob",
                          "Full GitHub Actions YAML"],
                         "File: `packages/cli/README.md`.",
                         "Manual review.",
                         deps="all monitor-cli features merged"),
                    task("docs(core): README explaining the workspace-only role", "P2", "XS", "low",
                         "monitor-core README — explains it's the shared base.",
                         "Consumers won't install this directly.",
                         ["Explain it ships transitively via monitor-node/browser",
                          "Public exports list (DSN parser, exception shaper, types)",
                          "Pointer to ADR-0001 for DSN format"],
                         "File: `packages/core/README.md`.",
                         "Manual review.",
                         deps="all monitor-core features merged"),
                ],
            },
            {
                "title": "Feature: Root docs",
                "priority": "P1", "effort": "M", "impact": "high",
                "body": body_feature(
                    goal="Root README + architecture.md + ADR 1 (DSN format) + ADR 2 (Sentry-shape over OTel).",
                    context="Architectural choices have to be documented so they can be revisited.",
                    acceptance=[
                        "Root README explains the install matrix",
                        "docs/architecture.md describes package boundaries + data flow",
                        "ADR-0001 explains DSN format",
                        "ADR-0002 explains Sentry-shaped API over OTel",
                    ],
                    tasks=[
                        "`docs(repo): root README — install matrix, quickstart`",
                        "`docs(repo): docs/architecture.md — package boundaries + data flow`",
                        "`docs(repo): docs/adr/0001-dsn-format.md`",
                        "`docs(repo): docs/adr/0002-sentry-shaped-api-over-otel.md`",
                    ],
                ),
                "tasks": [
                    task("docs(repo): root README — what's where, install matrix, quickstart", "P1", "S", "high",
                         "Top-level README for the repo.",
                         "First impression. Should be a map + quickstart.",
                         ["Install matrix table (use case → package)",
                          "3-line quickstart for each runtime (Node, Browser, React, CLI)",
                          "Link to per-package READMEs",
                          "Build + test instructions for contributors"],
                         "File: `README.md`.",
                         "Manual review.",
                         deps="all per-package READMEs"),
                    task("docs(repo): docs/architecture.md — package boundaries + data flow", "P1", "S", "medium",
                         "Architecture document for contributors.",
                         "Explains the why behind the package boundary lines.",
                         ["Diagram of packages + their dependencies",
                          "Sequence: captureException → scope snapshot → toOtlpLogRecord → exporter → backend",
                          "Trade-offs (Sentry-shape vs OTel, dual-build, workspace-only core)"],
                         "File: `docs/architecture.md`.",
                         "Manual review.",
                         deps="root README"),
                    task("docs(repo): docs/adr/0001-dsn-format.md", "P2", "XS", "low",
                         "ADR for the DSN format choice.",
                         "Future contributors will ask 'why nmk_ prefix?' — this answers it.",
                         ["Context: existing API token format (nmk_live_…)",
                          "Decision: nmk_<env>_<64hex>",
                          "Consequences"],
                         "File: `docs/adr/0001-dsn-format.md`. MADR format.",
                         "Manual review.",
                         deps="parseDsn merged"),
                    task("docs(repo): docs/adr/0002-sentry-shaped-api-over-otel.md", "P2", "XS", "low",
                         "ADR for the public API shape choice.",
                         "Doc the reason we wrap OTel rather than expose its API.",
                         ["Context: OTel API is verbose; operators know Sentry",
                          "Decision: Sentry-shaped wrappers, expose OTel via getOtelSdk()",
                          "Consequences: maintenance burden of the wrappers, but better DX"],
                         "File: `docs/adr/0002-sentry-shaped-api-over-otel.md`.",
                         "Manual review.",
                         deps="Neithly.init merged"),
                ],
            },
            {
                "title": "Feature: Example apps",
                "priority": "P2", "effort": "M", "impact": "medium",
                "body": body_feature(
                    goal="Two runnable example apps that double as integration tests.",
                    context="A real consumer's confidence in the SDK comes from a working example they can clone.",
                    acceptance=[
                        "examples/express-node — POST /api/order route that throws",
                        "examples/react-spa — Vite + react-router with an intentional bug",
                        "Each example has a README with the run command",
                    ],
                    tasks=[
                        "`docs(examples): examples/express-node — minimal POST with a throw`",
                        "`docs(examples): examples/react-spa — Vite + react-router + intentional bug`",
                    ],
                ),
                "tasks": [
                    task("docs(examples): examples/express-node — minimal POST /api/order with a throw", "P2", "S", "medium",
                         "Minimal Express app that demonstrates the integration.",
                         "Lives outside packages/* so it can pnpm-link the workspace packages.",
                         ["express + tsx for dev",
                          "Neithly.init in app.ts",
                          "expressErrorHandler wired",
                          "POST /api/order throws deterministically",
                          "README explains how to run + what to expect"],
                         "Folder: `examples/express-node/`. Use the monitor-node workspace package.",
                         "Manual: pnpm dev, curl POST /api/order, see event in backend.",
                         deps="monitor-node v0.1"),
                    task("docs(examples): examples/react-spa — Vite + react-router + intentional bug", "P2", "S", "medium",
                         "Minimal SPA demonstrating monitor-browser + monitor-react.",
                         "Vite + react-router; one route has a button that throws.",
                         ["Vite scaffold",
                          "monitor-browser init in main.tsx",
                          "<NeithlyErrorBoundary> at the app root",
                          "useTrackRouter installed",
                          "Bomb route throws on render",
                          "README explains run + capture"],
                         "Folder: `examples/react-spa/`.",
                         "Manual.",
                         deps="monitor-browser + monitor-react v0.1"),
                ],
            },
        ],
    },
]
